### ISSUE TITLE
Release a new tag for the package

### ISSUE THREAD

**Issue by Moundlen** [bjornvoesten/ciphersweet-for-laravel#12]
Hello, is it possible to release version 1.3.1 with support for php8 ?  Right now i need to require dev-master for the compatibility but there is a risk of breaking change in case of a composer update i would want to be able to fix this to a specific version.

Thank you

**Comment by bjornvoesten** [comment]
Should be fixed in https://github.com/bjornvoesten/ciphersweet-for-laravel/releases/tag/1.4.0
