### ISSUE TITLE
Nullable support

### ISSUE THREAD

**Issue by rickgoemans** [bjornvoesten/ciphersweet-for-laravel#3]
Hey Bjorn!

Ik zag net dat je deze package had toegevoegd naast de andere versie die je al had dus dacht ik ga even testen.
Ik heb alleen het probleem dat ik nu een veld tevens NULL wil laten toestaan.

Errors die ik vaak krijg zijn:
`Argument 1 passed to ParagonIE\ConstantTime\Binary::safeSubstr() must be of the type string, null given`

Heb jij suggesties?

**Comment by bjornvoesten** [comment]
Thank you creating this issue.

There was a problem when an attribute was null, the null value was passed to the underlying package, which could not handle this value.

This should be fixed in [1.2.0](https://github.com/bjornvoesten/ciphersweet-for-laravel/releases/tag/1.2.0 ).

**Comment by MasterBroki** [comment]
Hi @bjornvoesten , 

I found the same issue with a column containing an empty string. Is there a way to support that as well so it behaves the same as null values?

Thanks!
